on: 
  - push

name: build agent

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: |-
          cd agent
          cargo build --release
          cargo build --release --bin metaflow-agent-ctl
          ls -alh target/release
